// Module definitions for permission control
export interface ModuleDefinition {
  key: string;
  name: string;
  parent?: string;
}

export const modules: ModuleDefinition[] = [
  { key: "dashboard", name: "Home" },
  { key: "dashboards", name: "Dashboards" },
  { key: "dashboards.assets", name: "Asset Dashboard", parent: "dashboards" },
  { key: "dashboards.inventory", name: "Inventory Dashboard", parent: "dashboards" },
  { key: "dashboards.employees", name: "Employees Dashboard", parent: "dashboards" },
  { key: "dashboards.service", name: "Asset Service Dashboard", parent: "dashboards" },
  { key: "dashboards.store360", name: "Store 360 Dashboard", parent: "dashboards" },
  { key: "dashboards.vm", name: "VM Dashboard", parent: "dashboards" },
  { key: "dashboards.nso", name: "NSO Dashboard", parent: "dashboards" },
  { key: "pos", name: "Point of Sale" },
  { key: "pos.quicksale", name: "Quick Sale", parent: "pos" },
  { key: "pos.products", name: "Product Master", parent: "pos" },
  { key: "pos.orders", name: "Order History", parent: "pos" },
  { key: "pos.schemes", name: "Schemes", parent: "pos" },
  { key: "stores", name: "Store Management" },
  { key: "stores.all", name: "All Stores", parent: "stores" },
  { key: "stores.rentals", name: "Rentals & Leases", parent: "stores" },
  { key: "operations.tasks", name: "Task Master", parent: "stores" },
  { key: "operations.roles", name: "Role Master", parent: "stores" },
  { key: "operations.templates", name: "Task Templates", parent: "stores" },
  { key: "operations.adherence", name: "Task Adherence", parent: "stores" },
  { key: "operations.heatmap", name: "Store Heatmap", parent: "stores" },
  { key: "vm.planograms", name: "Planograms", parent: "stores" },
  { key: "vm.tasks", name: "Compliance Tasks", parent: "stores" },
  { key: "vm.review", name: "Compliance Audit", parent: "stores" },
  { key: "footfall", name: "Footfall", parent: "stores" },
  { key: "pettycash", name: "Petty Cash", parent: "stores" },
  { key: "stores.nso", name: "New Store Opening", parent: "stores" },
  { key: "expansion", name: "New Store Plan" },
  { key: "expansion.plans", name: "Store Plans", parent: "expansion" },
  { key: "expansion.franchisees", name: "Franchisees", parent: "expansion" },
  { key: "assets", name: "Assets & Service" },
  { key: "assets.master", name: "Asset Master", parent: "assets" },
  { key: "assets.register", name: "Asset Register", parent: "assets" },
  { key: "assets.contracts", name: "Service Contracts", parent: "assets" },
  { key: "assets.maintenance", name: "Preventive Maintenance", parent: "assets" },
  { key: "assets.tickets", name: "Service Tickets", parent: "assets" },
  { key: "assets.knowledge", name: "Knowledge Base", parent: "assets" },
  { key: "utilities", name: "Meter Readings", parent: "assets" },
  { key: "vendors", name: "Vendors" },
  { key: "staff", name: "Employee" },
  { key: "staff.employees", name: "Employees", parent: "staff" },
  { key: "staff.recruitment", name: "Recruitment", parent: "staff" },
  { key: "staff.performance", name: "Performance Reviews", parent: "staff" },
  { key: "staff.training", name: "Training Programs", parent: "staff" },
  { key: "staff.feedback", name: "Employee Feedback", parent: "staff" },
  { key: "staff.offboarding", name: "Offboarding", parent: "staff" },
  { key: "staff.lms", name: "Learning (LMS)", parent: "staff" },
  { key: "staff.attendance", name: "Attendance & Leave", parent: "staff" },
  { key: "security", name: "Security" },
  { key: "security.dashboard", name: "Security Dashboard", parent: "security" },
  { key: "security.guards", name: "Guards", parent: "security" },
  { key: "security.roster", name: "Roster", parent: "security" },
  { key: "security.patrol", name: "Patrol Points", parent: "security" },
  { key: "security.scan", name: "Patrol Scan", parent: "security" },
  { key: "security.feedback", name: "Feedback", parent: "security" },
  { key: "security.gamification", name: "Gamification", parent: "security" },
  { key: "inventory", name: "Inventory" },
  { key: "inventory.items", name: "Inventory Items", parent: "inventory" },
  { key: "inventory.requisitions", name: "Requisitions", parent: "inventory" },
  { key: "inventory.shipments", name: "Shipment Tracking", parent: "inventory" },
  { key: "inventory.grn", name: "Goods Receipt", parent: "inventory" },
  { key: "inventory.audit", name: "Stock Audit", parent: "inventory" },
  { key: "inventory.consumption", name: "Consumption Log", parent: "inventory" },
  { key: "inventory.expiry", name: "Expiry Management", parent: "inventory" },
  { key: "inventory.rtv", name: "Return to Vendor", parent: "inventory" },
  { key: "inventory.transfers", name: "Store Transfers", parent: "inventory" },
  { key: "inventory.alerts", name: "Low Stock Alerts", parent: "inventory" },
  { key: "master", name: "Master Data" },
  { key: "master.meter", name: "Meter Master", parent: "master" },
  { key: "master.department", name: "Department Master", parent: "master" },
  { key: "master.position", name: "Position Master", parent: "master" },
  { key: "master.category", name: "Category Master", parent: "master" },
  
  { key: "master.nso", name: "NSO Checklist Master", parent: "master" },
  { key: "master.pm", name: "PM Checklist Master", parent: "master" },
  { key: "usermanagement", name: "User Management" },
  { key: "usermanagement.users", name: "Users", parent: "usermanagement" },
  { key: "usermanagement.roles", name: "User Roles", parent: "usermanagement" },
  { key: "usermanagement.hierarchy", name: "User Hierarchy", parent: "usermanagement" },
  { key: "usermanagement.permissions", name: "Permission Set", parent: "usermanagement" },
  { key: "admin.company", name: "Company Information", parent: "admin" },
];

// Get parent modules only
export const parentModules = modules.filter((m) => !m.parent);

// Get child modules for a parent
export const getChildModules = (parentKey: string) =>
  modules.filter((m) => m.parent === parentKey);

// Route to module key mapping
export const routeToModuleKey: Record<string, string> = {
  "/": "dashboard",
  "/pos": "pos.quicksale",
  "/pos/products": "pos.products",
  "/pos/orders": "pos.orders",
  "/pos/schemes": "pos.schemes",
  "/stores": "stores.all",
  "/stores/rentals": "stores.rentals",
  "/stores/new-opening": "stores.nso",
  "/expansion/plans": "expansion.plans",
  "/expansion/franchisees": "expansion.franchisees",
  "/assets/master": "assets.master",
  "/assets/inventory": "assets.register",
  "/services/contracts": "assets.contracts",
  "/services/maintenance": "assets.maintenance",
  "/services/tickets": "assets.tickets",
  "/services/knowledge-base": "assets.knowledge",
  "/vendors": "vendors",
  "/petty-cash": "pettycash",
  "/utilities": "utilities",
  "/staff/employees": "staff.employees",
  "/staff/recruitment": "staff.recruitment",
  "/staff/performance": "staff.performance",
  "/staff/training": "staff.training",
  "/staff/feedback": "staff.feedback",
  "/staff/offboarding": "staff.offboarding",
  "/staff/attendance": "staff.attendance",
  "/security": "security.dashboard",
  "/security/guards": "security.guards",
  "/security/roster": "security.roster",
  "/security/patrol-points": "security.patrol",
  "/security/scan": "security.scan",
  "/security/feedback": "security.feedback",
  "/security/gamification": "security.gamification",
  "/footfall": "footfall",
  "/vm/planograms": "vm.planograms",
  "/vm/tasks": "vm.tasks",
  "/vm/review": "vm.review",
  "/inventory/items": "inventory.items",
  "/inventory/requisitions": "inventory.requisitions",
  "/inventory/shipments": "inventory.shipments",
  "/inventory/grn": "inventory.grn",
  "/inventory/audit": "inventory.audit",
  "/inventory/consumption": "inventory.consumption",
  "/inventory/expiry": "inventory.expiry",
  "/inventory/rtv": "inventory.rtv",
  "/inventory/transfers": "inventory.transfers",
  "/inventory/alerts": "inventory.alerts",
  "/operations/tasks": "operations.tasks",
  "/operations/roles": "operations.roles",
  "/operations/templates": "operations.templates",
  "/operations/adherence": "operations.adherence",
  "/operations/heatmap": "operations.heatmap",
  "/master/meter": "master.meter",
  "/master/department": "master.department",
  "/master/position": "master.position",
  "/master/category": "master.category",
  
  "/master/nso-checklist": "master.nso",
  "/master/pm-checklist": "master.pm",
  "/admin/users": "usermanagement.users",
  "/admin/roles": "usermanagement.roles",
  "/admin/hierarchy": "usermanagement.hierarchy",
  "/admin/permissions": "usermanagement.permissions",
  "/admin/company": "admin.company",
};
