
ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS style_no text,
  ADD COLUMN IF NOT EXISTS main_metal text,
  ADD COLUMN IF NOT EXISTS product_size text,
  ADD COLUMN IF NOT EXISTS colour text,
  ADD COLUMN IF NOT EXISTS gross_wt numeric,
  ADD COLUMN IF NOT EXISTS net_wt numeric,
  ADD COLUMN IF NOT EXISTS total_diamond_wt numeric,
  ADD COLUMN IF NOT EXISTS total_colour_stone_wt numeric,
  ADD COLUMN IF NOT EXISTS material_type text,
  ADD COLUMN IF NOT EXISTS material_quality text,
  ADD COLUMN IF NOT EXISTS material_inter_quality text,
  ADD COLUMN IF NOT EXISTS product_cert_no text,
  ADD COLUMN IF NOT EXISTS product_cert_by text,
  ADD COLUMN IF NOT EXISTS rm_cert_by text,
  ADD COLUMN IF NOT EXISTS rm_cert_no text,
  ADD COLUMN IF NOT EXISTS length numeric,
  ADD COLUMN IF NOT EXISTS material_weight numeric,
  ADD COLUMN IF NOT EXISTS material_pcs integer,
  ADD COLUMN IF NOT EXISTS item_price numeric,
  ADD COLUMN IF NOT EXISTS p_amount numeric,
  ADD COLUMN IF NOT EXISTS category_group text,
  ADD COLUMN IF NOT EXISTS material_rate numeric;
